name: forkstat
version: git
version-script: |
    echo $(git describe --tags)
summary: process fork/exec/exit monitoring tool
description: Forkstat monitors process fork(), exec() and exit() activity.  It is useful for monitoring system behaviour and to track down rogue processes that are spawning off processes and potentially abusing the system.
confinement: strict
type: app
grade: stable

parts:
    forkstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/forkstat
        build-packages:
            - gcc
            - make

apps:
    forkstat:
        command: usr/bin/forkstat
        plugs: [hardware-observe,netlink-connector,system-observe]
