name: forkstat
summary: process fork/exec/exit monitoring tool
description: Forkstat monitors process fork(), exec() and exit() activity.  It is useful for monitoring system behaviour and to track down rogue processes that are spawning off processes and potentially abusing the system.
confinement: strict
type: app
grade: stable
assumes: [snapd2.45]
base: core20
adopt-info: forkstat

parts:
    forkstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/forkstat
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make

apps:
    forkstat:
        command: usr/bin/forkstat
        plugs: [hardware-observe,netlink-connector,system-observe]
